---
AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::Serverless-2016-10-31'
Description: 'API Gateway -> Kinesis -> Lambda -> DB'

Resources:

  ###
  # API Gateway
  ###
  ApiAccount:
    Type: AWS::ApiGateway::Account
    Properties:
      # TODO:  Change to only access CloudWatch logs.
      CloudWatchRoleArn: !GetAtt ApiRole.Arn

  ApiRole:
    Type: AWS::IAM::Role
    Properties:
      Path: '/test/'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - apigateway.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: Kinesis
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - kinesis:PutRecord
                Resource:
                  - !GetAtt KinesisStream.Arn

  RestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: 'Api-Kinesis-Test'
      Description: 'Rest API for test.'
      EndpointConfiguration:
        Types:
          - REGIONAL

  ApiStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      StageName: Latest
      DeploymentId: !Ref ApiDeployment
      RestApiId: !Ref RestApi
      MethodSettings:
        - DataTraceEnabled: True
          HttpMethod: '*'
          MetricsEnabled: True
          ResourcePath: '/*'
          ThrottlingRateLimit: 10.0
          ThrottlingBurstLimit: 20
          LoggingLevel: INFO
      #Tags:
      #  - Key: String
      #    Value: String

  ApiDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - ItemPutMethod
    Properties:
      RestApiId: !Ref RestApi
      StageName: 'Pre-Prod'

  ###
  # API Validation
  ###
  BodyOnlyValidator:
    Type: AWS::ApiGateway::RequestValidator
    Properties:
      RestApiId: !Ref RestApi
      ValidateRequestBody: True
      ValidateRequestParameters: False

  ###
  # API Models
  ###
  ItemModel:
    Type: AWS::ApiGateway::Model
    Properties:
      ContentType: 'application/json'
      Description: 'Item for pass-through to Kinesis.'
      RestApiId: !Ref RestApi
      Schema:
        $schema: "http://json-schema.org/draft-07/schema#"
        title: Item
        description: 'Item for pass-through to Kinesis'
        type: object
        properties:
          id:
            description: 'The item ID.'
            type: integer
          description:
            description: 'A description of the item.'
            type: string
          count:
            description: 'How many items exist.'
            type: integer

  ###
  # API Resources
  ###

  ### /item
  ItemResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      PathPart: item
      ParentId: !GetAtt RestApi.RootResourceId
      RestApiId: !Ref RestApi

  ItemPutMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      ResourceId: !Ref ItemResource
      RestApiId: !Ref RestApi
      AuthorizationType: NONE
      HttpMethod: PUT
      RequestValidatorId: !Ref BodyOnlyValidator
      Integration:
        Type: AWS
        Credentials: !GetAtt ApiRole.Arn
        IntegrationHttpMethod: POST
        PassthroughBehavior: NEVER
        RequestParameters:
          'integration.request.header.Content-Type': "'application/x-amz-json-1.1'"
        RequestTemplates:
          'application/json': !Sub |
            #set($partitionKey = $context.requestId)
            {
                "StreamName": "${KinesisStream}",
                "Data": "$util.base64Encode($input.body)",
                "PartitionKey": "$partitionKey"
            }
        Uri: !Join
          - ':'
          - - 'arn:aws:apigateway'
            - !Ref 'AWS::Region'
            - 'kinesis'
            - 'action/PutRecord'
        IntegrationResponses:
          - StatusCode: 200
            SelectionPattern: '2\d{2}'
          - StatusCode: 400
            SelectionPattern: '4\d{2}'
          - StatusCode: 500
            SelectionPattern: '5\d{2}'
      OperationName: InsertItem
      RequestModels:
        'application/json': !Ref ItemModel
      MethodResponses:
        - StatusCode: 200
          ResponseModels:
            'application/json': Empty
        - StatusCode: 400
          ResponseModels:
            'application/json': Error
        - StatusCode: 500
          ResponseModels:
            'application/json': Error

  ###
  # Kinesis
  ###
  KinesisStream:
    Type: AWS::Kinesis::Stream
    Properties:
      RetentionPeriodHours: 24
      ShardCount: 1

  ###
  # Lambda Functions
  ###
  RustFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: 'Rust function for the API Gateway -> Kinesis -> Lambda test.'
      CodeUri: ./rust/target/lambda/release/gateway-kinesis-lambda-test.zip
      Runtime: provided
      Handler: NA
      MemorySize: 128
      Timeout: 30
      Role: !GetAtt RustFunctionRole.Arn
      Environment:
        Variables:
          LOG_LEVEL: DEBUG
      VpcConfig:
        SecurityGroupIds:
          - sg-48a2a02e
        SubnetIds:
          - subnet-00617c238bd96da41
          - subnet-022a1424b02344981

  RustFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      Path: '/test/'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/service-role/AWSLambdaENIManagementAccess
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: Kinesis
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - kinesis:DescribeStreamSummary
                  - kinesis:GetRecords
                  - kinesis:GetShardIterator
                  - kinesis:ListShards
                Resource:
                  - !GetAtt KinesisStream.Arn
              - Effect: Allow
                Action:
                  - kinesis:SubscribeToShard
                Resource:
                  - !GetAtt RustFunctionStreamConsumer.ConsumerARN

  RustFunctionStreamConsumer:
    Type: AWS::Kinesis::StreamConsumer
    Properties:
      ConsumerName: RustFunctionStreamConsumer
      StreamARN: !GetAtt KinesisStream.Arn

  RustFunctionEvents:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      Enabled: true
      EventSourceArn: !GetAtt RustFunctionStreamConsumer.ConsumerARN
      FunctionName: !GetAtt RustFunction.Arn
      StartingPosition: LATEST
      BatchSize: 100
